apiVersion: neuronex.emqx.io/v1alpha1
kind: NeuronEX
metadata:
  name: {{ include "neuronex.fullname" . }}
  labels:
    {{- include "neuronex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets: {{ .Values.imagePullSecrets }}
  {{- end }}
  {{- if .Values.env }}
  env: {{- toYaml .Values.env | nindent 2 }}
  {{- end }}
  {{- if .Values.resources }}
  resources: {{-  toYaml .Values.resources | nindent 4 }}
  {{- end }}
  {{- if .Values.initContainers }}
  initContainers: {{- toYaml .Values.initContainers | nindent 2 }}
  {{- end }}
  {{- if .Values.externalContainers }}
  externalContainers: {{- toYaml .Values.externalContainers | nindent 2 }}
  {{- end }}
  {{- if .Values.affinity }}
  affinity: {{- toYaml .Values.affinity | nindent 4 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations: {{- toYaml .Values.tolerations | nindent 2 }}
  {{- end }}
  {{- if .Values.nodeSelector }}
  nodeSelector: {{- toYaml .Values.nodeSelector | nindent 4 }}
  {{- end }}
  {{- if .Values.nodeName }}
  nodeName: {{ .Values.nodeName }}
  {{- end }}

  {{- if .Values.livenessProbe }}
  livenessProbe: {{- toYaml .Values.livenessProbe | nindent 2 }}
  {{- end }}
  {{- if .Values.readinessProbe }}
  readinessProbe: {{- toYaml .Values.readinessProbe | nindent 2 }}
  {{- end }}
  {{- if .Values.startupProbe }}
  startupProbe: {{- toYaml .Values.startupProbe | nindent 2 }}
  {{- end }}

  {{- if not .Values.auth.enabled }}
  disableAuth: true
  {{- end }}
  {{- if .Values.auth.jwt }}
  jwt: {{- toYaml .Values.auth.jwt | nindent 2 }}
  {{- end }}

  {{- if .Values.storageClass.enabled }}
  {{- with .Values.storageClass }}
  {{- if .name }}
  storageClassName: {{ .name }}
  {{- end }}
  {{- if .accessMode }}
  volumeClaimAccessModes: {{ .accessModes }}
  {{- end }}
  {{- if .size }}
  volumeSize: {{ .size }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- if .Values.volumeClaimTemplates }}
  volumeClaimTemplates: {{- toYaml .Values.volumeClaimTemplates | nindent 2 }}
  {{- end }}

  {{- if .Values.externalVolumes }}
  externalVolumes: {{- toYaml .Values.externalVolumes | nindent 2 }}
  {{- end }}

  {{- if .Values.externalVolumeMounts }}
  externalVolumeMounts: {{- toYaml .Values.externalVolumeMounts | nindent 2 }}
  {{- end }}

  {{- if .Values.podSecurityContext }}
  securityContext: {{- toYaml .Values.podSecurityContext | nindent 4 }}
  {{- end }}
  {{- if .Values.securityContext }}
  containerSecurityContext: {{- toYaml .Values.securityContext | nindent 4 }}
  {{- end }}

  {{- if .Values.services }}
  services: {{- toYaml .Values.services | nindent 2 }}
  {{- end }}
